"""Fail closed on pyright regressions without blocking on known residuals.

The typecheck job is a branch-protection required context. continue-on-error
made that context vacuous: 82 residuals still greened the check. A count-only
cap is occupancy: any 82 errors pass, including a full turnover of the set.

This script is the actual gate. It runs pyright and exits 1 if:

- errorCount exceeds MAX_ERRORS, or
- any error identity (relative-file:rule) is missing from
  tools/pyright_baseline.txt (new residual class, even when count stays
  at the cap)

Every run prints the diagnostic list (file:rule:message) and an identity
hash so CI can tell which errors, not only N. Lower the cap and prune the
baseline when residuals are paid down. Never raise MAX_ERRORS without a
tracked finding. Do not restore continue-on-error. Do not add a pytest job.

Usage: python tools/check_pyright_gate.py [path] [--write-baseline]
"""
from __future__ import annotations

import hashlib
import json
import pathlib
import subprocess
import sys

# Measured 2026-09-15 on this worktree (pyright 1.1.414, typeCheckingMode=basic):
# 82 errors / 3 warnings / 45 files. Ratchet down; never up.
# tools/check_ci_policy.py refuses MAX_ERRORS above this literal.
MAX_ERRORS = 82
ROOT = pathlib.Path(__file__).resolve().parents[1]
BASELINE_PATH = ROOT / "tools" / "pyright_baseline.txt"

_argv = sys.argv[1:]
WRITE_BASELINE = "--write-baseline" in _argv
TARGET = next((a for a in _argv if a != "--write-baseline"), "audiobooker")


def _rel_file(path_str: str) -> str:
    path = pathlib.Path(path_str)
    try:
        path = path.resolve().relative_to(ROOT)
    except ValueError:
        pass
    return path.as_posix()


def diagnostic_key(diag: dict) -> str:
    """Baseline identity: path + rule. Line numbers and message wording churn."""
    file = _rel_file(str(diag.get("file") or ""))
    rule = str(diag.get("rule") or diag.get("code") or "")
    return f"{file}:{rule}"


def diagnostic_line(diag: dict) -> str:
    """Log line: path + rule + message. Printed on every run (success and RED)."""
    key = diagnostic_key(diag)
    message = " ".join(str(diag.get("message") or "").split())
    return f"{key}:{message}"


def load_baseline(path: pathlib.Path) -> set[str]:
    identities: set[str] = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        identities.add(line)
    return identities


def write_baseline(path: pathlib.Path, identities: list[str]) -> None:
    lines = [
        "# Pyright error identities (file:rule). Sorted.",
        "# Generated by tools/check_pyright_gate.py --write-baseline.",
        "# New identities redden typecheck even when count stays at the cap.",
        "# Paying one down is not a raise — prune this file and lower MAX_ERRORS.",
        *identities,
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    proc = subprocess.run(
        ["pyright", TARGET, "--outputjson"],
        capture_output=True,
        text=True,
    )
    raw = proc.stdout.strip()
    try:
        start = raw.index("{")
        data = json.loads(raw[start:])
    except (ValueError, json.JSONDecodeError):
        sys.stderr.write(proc.stdout)
        sys.stderr.write(proc.stderr)
        sys.stderr.write("pyright did not emit parseable JSON\n")
        return proc.returncode or 1

    diagnostics = [
        d
        for d in data.get("generalDiagnostics") or []
        if str(d.get("severity", "error")).lower() == "error"
    ]
    keys = sorted({diagnostic_key(d) for d in diagnostics})
    lines = [diagnostic_line(d) for d in diagnostics]
    lines.sort()
    digest = hashlib.sha256("\n".join(lines).encode("utf-8")).hexdigest()
    count = int(data.get("summary", {}).get("errorCount", 0))

    # Always dump. Success used to print only "pyright errors: N (cap 82)",
    # so a residual turnover was invisible. RED also omitted generalDiagnostics.
    print(f"pyright errors: {count} (cap {MAX_ERRORS})")
    print(f"pyright identity-sha256: {digest} ({len(keys)} file:rule)")
    print("pyright diagnostics:")
    if lines:
        for item in lines:
            print(f"  {item}")
    else:
        print("  (none)")

    if WRITE_BASELINE:
        write_baseline(BASELINE_PATH, keys)
        print(
            f"wrote {BASELINE_PATH.relative_to(ROOT).as_posix()} "
            f"({len(keys)} identities)"
        )
        return 0

    if not BASELINE_PATH.is_file():
        sys.stderr.write(
            f"{BASELINE_PATH.name} missing. "
            "Run: python tools/check_pyright_gate.py --write-baseline\n"
        )
        return 1

    baseline = load_baseline(BASELINE_PATH)
    new = [item for item in keys if item not in baseline]
    paid = sorted(baseline - set(keys))

    if new:
        sys.stderr.write(
            f"pyright new error identities ({len(new)}) not in "
            f"{BASELINE_PATH.name} (count-only occupancy is not enough):\n"
        )
        for item in new:
            sys.stderr.write(f"  {item}\n")
        return 1

    if count > MAX_ERRORS:
        sys.stderr.write(
            f"pyright error count {count} exceeds cap {MAX_ERRORS}. "
            "New type errors on a required check.\n"
        )
        return 1

    if count < MAX_ERRORS:
        print(
            f"note: {MAX_ERRORS - count} below cap — lower MAX_ERRORS in "
            "tools/check_pyright_gate.py to ratchet the gate."
        )
    if paid:
        print(
            f"note: {len(paid)} baseline identities gone — prune "
            f"{BASELINE_PATH.name} to match."
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
